title: MECO MISTI Workshop 2024
description: ""
baseurl: ""
url: https://meco-group.github.io/mit-impact-2024/

theme: jekyll-nagymaros

copyright: MECO Research Team
indexing: true

exclude:
  - jekyll-nagymaros.gemspec
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
