title: MECO MISTI Workshop 2024
description: "Website for the workshop given by the MECO Research Team of KU Leuven, held at MIT in July 2024"
baseurl: ""
url: https://meco-group.github.io/mit-impact-2024/

theme: jekyll-nagymaros

copyright: Place Holder
indexing: true

exclude:
  - demo/
  - jekyll-nagymaros.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
